# Generated by Django 4.1 on 2024-04-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountTable",
            fields=[
                (
                    "email",
                    models.CharField(
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        verbose_name="邮件",
                    ),
                ),
                ("nickname", models.CharField(max_length=10, verbose_name="昵称")),
                ("psword", models.CharField(max_length=100, verbose_name="密码")),
                ("rgtime", models.DateField(auto_now_add=True, verbose_name="注册时间")),
                ("power", models.IntegerField(verbose_name="权限等级")),
            ],
        ),
        migrations.CreateModel(
            name="CityTable",
            fields=[
                (
                    "city",
                    models.CharField(
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                        verbose_name="城市",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CityCountyTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=5, verbose_name="县名")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.citytable",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="citycountytable",
            constraint=models.UniqueConstraint(
                fields=("city", "county"), name="uniqueCityCounty"
            ),
        ),
    ]
