# Generated by Django 4.1 on 2024-04-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountTable",
            fields=[
                (
                    "email",
                    models.CharField(
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        verbose_name="邮件",
                    ),
                ),
                ("nickname", models.CharField(max_length=30, verbose_name="昵称")),
                ("password", models.CharField(max_length=300, verbose_name="密码")),
                ("register", models.DateField(auto_now_add=True, verbose_name="注册时间")),
                ("power", models.IntegerField(verbose_name="权限等级")),
            ],
            options={
                "verbose_name": "账号",
                "verbose_name_plural": "账号",
            },
        ),
        migrations.CreateModel(
            name="CityTable",
            fields=[
                (
                    "city",
                    models.CharField(
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                        verbose_name="城市",
                    ),
                ),
            ],
            options={
                "verbose_name": "城市",
                "verbose_name_plural": "城市",
            },
        ),
        migrations.CreateModel(
            name="CodeTable",
            fields=[
                (
                    "email",
                    models.CharField(
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        verbose_name="用户邮箱",
                    ),
                ),
                ("code", models.CharField(max_length=100, verbose_name="验证码")),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="输入时间")),
            ],
            options={
                "verbose_name": "验证码",
                "verbose_name_plural": "验证码",
            },
        ),
        migrations.CreateModel(
            name="ServiceTable",
            fields=[
                (
                    "service",
                    models.CharField(
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        verbose_name="服务",
                    ),
                ),
            ],
            options={
                "verbose_name": "服务",
                "verbose_name_plural": "服务",
            },
        ),
        migrations.CreateModel(
            name="DoctorTable",
            fields=[
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="client.accounttable",
                        verbose_name="账户",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="姓名")),
                ("birthday", models.DateField(verbose_name="生日")),
                ("edubackground", models.IntegerField(verbose_name="学历")),
                ("introduction", models.CharField(max_length=300, verbose_name="介绍")),
            ],
            options={
                "verbose_name": "医生",
                "verbose_name_plural": "医生",
            },
        ),
        migrations.CreateModel(
            name="ClinicTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("county", models.CharField(max_length=10, verbose_name="县")),
                ("location", models.CharField(max_length=60, verbose_name="地点")),
                ("time", models.CharField(max_length=60, verbose_name="营业时间")),
                ("name", models.CharField(max_length=30, verbose_name="诊所名称")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.citytable",
                        verbose_name="城市",
                    ),
                ),
            ],
            options={
                "verbose_name": "诊所",
                "verbose_name_plural": "诊所",
            },
        ),
        migrations.CreateModel(
            name="ClinicServiceTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.clinictable",
                        verbose_name="诊所",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.servicetable",
                        verbose_name="服务",
                    ),
                ),
            ],
            options={
                "verbose_name": "诊所服务",
                "verbose_name_plural": "诊所服务",
            },
        ),
        migrations.CreateModel(
            name="ClinicDoctorTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("starttime", models.TimeField(verbose_name="开始时间")),
                ("endtime", models.TimeField(verbose_name="结束时间")),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.clinictable",
                        verbose_name="诊所",
                    ),
                ),
            ],
            options={
                "verbose_name": "诊所医生",
                "verbose_name_plural": "诊所医生",
            },
        ),
        migrations.CreateModel(
            name="CityCountyTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=5, verbose_name="县")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.citytable",
                        verbose_name="城市",
                    ),
                ),
            ],
            options={
                "verbose_name": "县",
                "verbose_name_plural": "县",
            },
        ),
        migrations.CreateModel(
            name="AppointmentTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.CharField(max_length=30, verbose_name="预约时间")),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.clinictable",
                        verbose_name="预约诊所",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.accounttable",
                        verbose_name="预约者",
                    ),
                ),
            ],
            options={
                "verbose_name": "预约",
                "verbose_name_plural": "预约",
            },
        ),
        migrations.CreateModel(
            name="DoctorServiceTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.servicetable",
                        verbose_name="服务",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.doctortable",
                        verbose_name="医生",
                    ),
                ),
            ],
            options={
                "verbose_name": "医生服务",
                "verbose_name_plural": "医生服务",
            },
        ),
        migrations.AddConstraint(
            model_name="clinicservicetable",
            constraint=models.UniqueConstraint(
                fields=("clinic", "service"), name="uniqueClinicService"
            ),
        ),
        migrations.AddField(
            model_name="clinicdoctortable",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="client.doctortable",
                verbose_name="医生",
            ),
        ),
        migrations.AddConstraint(
            model_name="citycountytable",
            constraint=models.UniqueConstraint(
                fields=("city", "county"), name="uniqueCityCounty"
            ),
        ),
        migrations.AddField(
            model_name="appointmenttable",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="client.doctortable",
                verbose_name="预约医生",
            ),
        ),
        migrations.AddConstraint(
            model_name="doctorservicetable",
            constraint=models.UniqueConstraint(
                fields=("doctor", "service"), name="uniqueDoctorService"
            ),
        ),
        migrations.AddConstraint(
            model_name="clinicdoctortable",
            constraint=models.UniqueConstraint(
                fields=("clinic", "doctor", "date", "starttime", "endtime"),
                name="uniqueClinicDoctor",
            ),
        ),
    ]
