# Generated by Django 4.1 on 2024-04-19 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CityCountyTable",
        ),
    ]
