# Generated by Django 4.1 on 2024-04-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicdoctortable",
            name="appointment",
            field=models.BooleanField(default=0, verbose_name="是否被预约"),
        ),
    ]
