# Generated by Django 4.1 on 2024-04-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_delete_citycountytable"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityCountyTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=5, verbose_name="县名")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.citytable",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="citycountytable",
            constraint=models.UniqueConstraint(
                fields=("city", "county"), name="uniqueCityCounty"
            ),
        ),
    ]
