# Generated by Django 4.1 on 2024-04-23 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_clinicdoctortable_appointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmenttable",
            name="time",
        ),
    ]
