# Generated by Django 4.1 on 2024-04-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_remove_appointmenttable_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmenttable",
            name="endtime",
            field=models.TimeField(default="12:30:00", verbose_name="结束时间"),
        ),
        migrations.AddField(
            model_name="appointmenttable",
            name="starttime",
            field=models.TimeField(default="12:00:00", verbose_name="开始时间"),
        ),
    ]
