# Generated by Django 4.1 on 2024-04-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0004_codetable_alter_citycountytable_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codetable",
            name="email",
            field=models.CharField(
                max_length=30, primary_key=True, serialize=False, verbose_name="用户邮箱"
            ),
        ),
        migrations.AlterField(
            model_name="codetable",
            name="time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="输入时间"),
        ),
    ]
