# Generated by Django 4.1 on 2024-04-23 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0005_messagetable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messagetable",
            options={"verbose_name": "信息", "verbose_name_plural": "信息"},
        ),
    ]
