# Generated by Django 4.1 on 2024-04-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0006_alter_messagetable_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetable",
            name="read",
            field=models.BooleanField(default=0, verbose_name="已读"),
        ),
    ]
