# Generated by Django 4.1 on 2024-04-20 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0006_rename_psword_accounttable_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("county", models.CharField(max_length=10)),
                ("location", models.CharField(max_length=60)),
                ("time", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=30)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.citytable",
                        verbose_name="城市",
                    ),
                ),
            ],
        ),
    ]
