# Generated by Django 4.1 on 2024-04-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0007_messagetable_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetable",
            name="title",
            field=models.CharField(default="", max_length=30, verbose_name="标题"),
        ),
    ]
