# Generated by Django 4.1 on 2024-04-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0008_alter_accounttable_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinictable",
            name="county",
            field=models.CharField(max_length=10, verbose_name="县"),
        ),
        migrations.AlterField(
            model_name="clinictable",
            name="location",
            field=models.CharField(max_length=60, verbose_name="地点"),
        ),
        migrations.AlterField(
            model_name="clinictable",
            name="name",
            field=models.CharField(max_length=30, verbose_name="诊所名称"),
        ),
        migrations.AlterField(
            model_name="clinictable",
            name="time",
            field=models.CharField(max_length=60, verbose_name="营业时间"),
        ),
    ]
