# Generated by Django 4.1 on 2024-04-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0008_messagetable_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetable",
            name="type",
            field=models.IntegerField(default=0, verbose_name="类型"),
        ),
    ]
