# Generated by Django 4.1 on 2024-04-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0010_doctortable_professor"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="doctortable",
            name="professor",
        ),
    ]
