# Generated by Django 4.1 on 2024-04-26 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0011_commenttable_remove_doctortable_professor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommentTable",
        ),
    ]
