# Generated by Django 4.1 on 2024-04-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0014_appointmenttable_delete_clinicdoctortable_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointmenttable",
            options={"verbose_name": "预约", "verbose_name_plural": "预约"},
        ),
        migrations.RemoveField(
            model_name="appointmenttable",
            name="appointment",
        ),
        migrations.AddField(
            model_name="accounttable",
            name="name",
            field=models.CharField(default="张三", max_length=30, verbose_name="姓名"),
        ),
        migrations.AddField(
            model_name="appointmenttable",
            name="service",
            field=models.ForeignKey(
                default="镶牙",
                on_delete=django.db.models.deletion.CASCADE,
                to="client.servicetable",
                verbose_name="服务",
            ),
        ),
        migrations.AddField(
            model_name="appointmenttable",
            name="stage",
            field=models.IntegerField(default=0, verbose_name="阶段"),
        ),
        migrations.AlterField(
            model_name="appointmenttable",
            name="patient",
            field=models.ForeignKey(
                default="chiking0718@163.com",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="client.accounttable",
                verbose_name="病人",
            ),
        ),
    ]
