# Generated by Django 4.1 on 2024-04-27 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0015_alter_appointmenttable_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("mark", models.IntegerField(verbose_name="分数")),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="评价时间")),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.appointmenttable",
                        verbose_name="预约",
                    ),
                ),
            ],
            options={
                "verbose_name": "评价",
                "verbose_name_plural": "评价",
            },
        ),
    ]
