# Generated by Django 4.1 on 2024-04-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0016_commenttable"),
    ]

    operations = [
        migrations.AddField(
            model_name="commenttable",
            name="content",
            field=models.CharField(default="", max_length=300, verbose_name="内容"),
        ),
    ]
