# Generated by Django 4.1 on 2024-04-27 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0017_commenttable_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="commenttable",
            name="committer",
            field=models.ForeignKey(
                default="chiking0718@163.com",
                on_delete=django.db.models.deletion.CASCADE,
                to="client.accounttable",
                verbose_name="提交者",
            ),
        ),
    ]
