# Generated by Django 4.1 on 2024-04-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0018_commenttable_committer"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctortable",
            name="title",
            field=models.IntegerField(default=2, verbose_name="职称"),
        ),
    ]
