# Generated by Django 4.1 on 2024-04-29 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0020_startable_liketable_followtable"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowLikeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.accounttable",
                        verbose_name="评价人",
                    ),
                ),
                (
                    "follow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.followtable",
                        verbose_name="回复",
                    ),
                ),
            ],
            options={
                "verbose_name": "回复点赞",
                "verbose_name_plural": "回复点赞",
            },
        ),
    ]
