# Generated by Django 4.1 on 2024-05-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0021_followliketable"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackstageAccountTable",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        primary_key=True,
                        serialize=False,
                        verbose_name="邮件",
                    ),
                ),
                ("nickname", models.CharField(max_length=30, verbose_name="昵称")),
                ("power", models.IntegerField(verbose_name="权限")),
                ("password", models.CharField(max_length=30, verbose_name="密码")),
            ],
            options={
                "verbose_name": "后台账户",
                "verbose_name_plural": "后台账户",
            },
        ),
    ]
