# Generated by Django 4.1 on 2024-05-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0023_backstagecookietable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followliketable",
            name="time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="时间"),
        ),
        migrations.CreateModel(
            name="BackstageApplicationTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="发送时间")),
                (
                    "receive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.clinictable",
                        verbose_name="诊所",
                    ),
                ),
                (
                    "send",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.backstageaccounttable",
                        verbose_name="发送者",
                    ),
                ),
            ],
            options={
                "verbose_name": "医生申请",
                "verbose_name_plural": "医生申请",
            },
        ),
    ]
