# Generated by Django 4.1 on 2024-05-12 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0024_alter_followliketable_time_backstageapplicationtable"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicDoctorTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.clinictable",
                        verbose_name="诊所",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.doctortable",
                        verbose_name="医生",
                    ),
                ),
            ],
            options={
                "verbose_name": "诊所医生",
                "verbose_name_plural": "诊所医生",
            },
        ),
    ]
